default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: <%= ENV['DATABASE_SOCKET'] %>

development:
  <<: *default
  database: medium_development

test:
  <<: *default
  database: medium_test

production:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_URL'] %>
  port: <%= ENV['DB_PORT'] %>
