validations:
  user:
    min_age: 10
    email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
    name_minlength: 5
    name_maxlength: 50
    email_minlength: 5
    email_maxlength: 255
    bio_maxlength: 200
    password_minlength: 6
    password_maxlength: 255
